name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: FrodoBeutlinAliasLeon
          outputs: dist/github-snake-dark.svg?palette=github-dark&color_snake=#d1d1d1&color_dots=#161b22,#ff4d00,#ff7b00,#ff9d00,#ffb347
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
